# This workflow will build the Node project and publish the current tagged
# release to npm

name: publish

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          # This is critical to have in the publish step, because otherwise the
          # Bible data will not be included in the published npm tarball
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build & publish to npm
        # Adding --no-git-checks solves a weird ERR_PNPM_GIT_UNKNOWN_BRANCH
        # error
        run: pnpm publish --no-git-checks
